function MASK = eclispeUnsharpMask(IMG, IMG_INFO, CONFIG)

IMG = im2gray(IMG);

EST = eclipseDiskDetection(IMG, CONFIG);

[~, MASK] = imgSpinBlur( ...
    IMG,                    ...
    EST.X0,                              ...
    EST.Y0,                              ...
    CONFIG.PARAM.REG.PREP.SPIN_BLUR_ANG, ...
    1,                                   ...
    (2^(IMG_INFO.BitDepth/3)) / 2,       ...
    CONFIG.PARAM.REG.DEBUG               ...
);

end