function [IMG_DATA, CONFIG] = SETIP_REG_PRE(IMG_DATA, CONFIG)

if CONFIG.PARAM.REG.IMPORT == false

% == IMAGE PRE-PROCESSING: ==============================================

% TBD:
    IMG_DATA.PRE.DATA = cell(IMG_DATA.IMG_CNT, 1);

% TBD:
for i = 1:1:IMG_DATA.IMG_CNT
% TBD:
    clc;
    fprintf('Pre-Processing image %2.0f of %2.0f ...\n', ...
        i, IMG_DATA.IMG_CNT);
% TBD:
    IMG_DATA.PRE.DATA{i} = IMG_DATA.RAW.DATA{i};
% TBD:
    IMG_DATA.PRE.DATA{i} = im2gray( ...
        IMG_DATA.PRE.DATA{i} ...
    );
% TBD:
    IMG_DATA.PRE.DATA{i} = adapthisteq( ...
        IMG_DATA.PRE.DATA{i}, ...
        'NumTiles', [6,6], ...
        'ClipLimit', 0.01, ...
        'NBins', 2^8, ...
        'Range', 'full', ...
        'Distribution', 'uniform' ...
    );
% TBD:
    if i == 1
        EST = eclipseDiskDetection( ...
            IMG_DATA.PRE.DATA{i}, ...
            CONFIG ...
        );
        diskRadiusWithMarg = ...
            EST.A * (1 + (2 * CONFIG.PARAM.REG.PREP.CROP_MARGIN));
        cropX0           = EST.X0 - diskRadiusWithMarg;
        cropY0           = EST.Y0 - diskRadiusWithMarg;
        cropWidth        = 2*diskRadiusWithMarg;
        cropHeight       = 2*diskRadiusWithMarg;
    end
    IMG_DATA.PRE.DATA{i} = imcrop( ...
        IMG_DATA.PRE.DATA{i}, ...
        [ ...
          cropX0,    ...
          cropY0,    ...
          cropWidth, ...
          cropHeight ...
        ] ...
    );
% TBD:
    % IMG_DATA.PRE.DATA{i} = eclispeUnsharpMask(...
    %     IMG_DATA.PRE.DATA{i}, ...
    %     IMG_DATA.INFO{i}, ...
    %     CONFIG ...
    % );
% TBD:
    % waitfor(imshow(IMG_DATA.PRE.DATA{i}));
end

end