function [IMG_DATA, CONFIG] = SETIP_REG_PST(IMG_DATA, CONFIG)

% TBD:
    IMG_DATA.POST.DATA = cell(IMG_DATA.IMG_CNT, 1);

for i = 1:1:IMG_DATA.IMG_CNT
% TBD:
    clc; fprintf('Post-registration processing image %2.0f of %2.0f ...\n', ...
        i, IMG_DATA.IMG_CNT);
% TBD:
    IMG_DATA.POST.DATA{i} = IMG_DATA.REG.DATA{i};
% TBD:
    % TBD:
        MASK = eclispeUnsharpMask( ...
            IMG_DATA.POST.DATA{i}, ...
            IMG_DATA.INFO{i},               ...
            CONFIG                          ...
        );
    % TBD:
        IMG_DATA.POST.DATA{i} = imblend( ...
            MASK,                  ...
            IMG_DATA.POST.DATA{i}, ...
            1,                     ...
            'soft light eb2',      ...
            2                      ...
        );
% TBD:
    IMG_TEMP = rgb2lab(IMG_DATA.POST.DATA{i});
    MAX_L = 100;
    L = IMG_TEMP(:, :, 1) / MAX_L;
    IMG_TEMP(:,:,1) = adapthisteq(L, ...
        'NumTiles'    , [10, 10], ...
        'ClipLimit'   , 0.0050, ...
        'NBins'       , 256, ...
        'Range'       , 'full', ...
        'Distribution', 'rayleigh', ...
        'Alpha'       , 0.40...
    ) * MAX_L;
    IMG_DATA.POST.DATA{i} = lab2rgb(IMG_TEMP);
end

end